// flow-typed signature: 2e53321732fb022624b7e0f1217466dd
// flow-typed version: <<STUB>>/is-generator-function_v^1.0.7/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'is-generator-function'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'is-generator-function' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'is-generator-function/test/corejs' {
  declare module.exports: any;
}

declare module 'is-generator-function/test/index' {
  declare module.exports: any;
}

declare module 'is-generator-function/test/uglified' {
  declare module.exports: any;
}

// Filename aliases
declare module 'is-generator-function/index' {
  declare module.exports: $Exports<'is-generator-function'>;
}
declare module 'is-generator-function/index.js' {
  declare module.exports: $Exports<'is-generator-function'>;
}
declare module 'is-generator-function/test/corejs.js' {
  declare module.exports: $Exports<'is-generator-function/test/corejs'>;
}
declare module 'is-generator-function/test/index.js' {
  declare module.exports: $Exports<'is-generator-function/test/index'>;
}
declare module 'is-generator-function/test/uglified.js' {
  declare module.exports: $Exports<'is-generator-function/test/uglified'>;
}
