language: node_js
cache:
  directories:
  - node_modules # NPM packages
node_js:
  - 6.0
  - 6.9
  - 7.0
  - 7.1
matrix:
  fast_finish: true
  include:
    - addons:
        mariadb: 10.0
      env: MYSQL_USER=root MYSQL_PASS=''
    - dist: trusty
      group: edge # until the next update
      env: MYSQL_USER=root MYSQL_PASS=''
      services:
        - mysql
      addons:
        apt:
          packages:
            - mysql-server-5.6
            - mysql-client-core-5.6
            - mysql-client-5.6

before_script:
 - mysql -u root -e 'create database minorm_test;'
install:
  - npm install -g codecov
  - npm install -g babel-cli
  - npm install -g istanbul
  - npm install -g mocha
  - npm install -g flow-bin
  - npm install
script:
  - npm test
  - flow check
after_success:
  - codecov
after_script:
  - mysql -u root -e 'drop database minorm_test;'
