language: node_js
cache:
  directories:
  - node_modules # NPM packages
matrix:
  fast_finish: true
  include:
    - addons:
        mariadb: 10.0
      env: DB=mariadb NODE=6.0 MYSQL_USER=root MYSQL_PASS=''
      node_js:
        - 6.0
    - addons:
        mariadb: 10.0
      env: DB=mariadb NODE=6.9 MYSQL_USER=root MYSQL_PASS=''
      node_js:
        - 6.9
    - addons:
        mariadb: 10.0
      env: DB=mariadb NODE=8.0 MYSQL_USER=root MYSQL_PASS=''
      node_js:
        - 8.0
    - addons:
        mariadb: 10.0
      env: DB=mariadb NODE=8.9 MYSQL_USER=root MYSQL_PASS=''
      node_js:
        - 8.9
    # - dist: trusty
    #   sudo: required
    #   group: edge # until the next update
    #   env: DB=mysql56 NODE=6.0 MYSQL_HOST=0.0.0.0 MYSQL_USER=root MYSQL_PASS=''
    #   services:
    #     - mysql
    #   addons:
    #     apt:
    #       packages:
    #         - mysql-server-5.6
    #         - mysql-client-core-5.6
    #         - mysql-client-5.6
    #   node_js:
    #     - 6.0
    # - dist: trusty
    #   sudo: required
    #   group: edge # until the next update
    #   env: DB=mysql56 NODE=6.9 MYSQL_HOST=0.0.0.0 MYSQL_USER=root MYSQL_PASS=''
    #   addons:
    #     apt:
    #       packages:
    #         - mysql-server-5.6
    #         - mysql-client-core-5.6
    #         - mysql-client-5.6
    #   node_js:
    #     - 6.9

before_script:
 - mysql -u root -e 'create database minorm_test;'
install:
  - npm install -g codecov
  - npm install -g babel-cli
  - npm install -g istanbul
  - npm install -g mocha
  - npm install -g flow-bin
  - npm install
script:
  - npm test
  - flow check
after_success:
  - codecov
after_script:
  - mysql -u root -e 'drop database minorm_test;'
