language: node_js
cache:
  directories:
  - node_modules # NPM packages
matrix:
  fast_finish: true
  include:
    - addons:
        mariadb: 10.0
      env: DB=mariadb NODE=6.0 MYSQL_USER=root MYSQL_PASS=''
      node_js:
        - 6.10
    - addons:
        mariadb: 10.0
      env: DB=mariadb NODE=6.9 MYSQL_USER=root MYSQL_PASS=''
      node_js:
        - 6.12
    - addons:
        mariadb: 10.0
      env: DB=mariadb NODE=8.0 MYSQL_USER=root MYSQL_PASS=''
      node_js:
        - 8.0
    - addons:
        mariadb: 10.0
      env: DB=mariadb NODE=8.9 MYSQL_USER=root MYSQL_PASS=''
      node_js:
        - 8
    - services:
        - mysql
      env: DB=mysql NODE=8.9 MYSQL_USER=root MYSQL_PASS=''
      node_js:
        - 8


before_script:
 - mysql -u root -e 'create database minorm_test;'
install:
  - npm i -g yarn
  - yarn global add codecov
  - yarn install
script:
  - yarn test
  - yarn lint
  - yarn flow check
after_success:
  - codecov
after_script:
  - mysql -u root -e 'drop database minorm_test;'
