// flow-typed signature: 4cbe75e869c35d34370189133c2a62ed
// flow-typed version: <<STUB>>/array-aggregate_v^0.1.7/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'array-aggregate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'array-aggregate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'array-aggregate/lib/index' {
  declare module.exports: any;
}

declare module 'array-aggregate/lib/makeQueryFilter' {
  declare module.exports: any;
}

declare module 'array-aggregate/lib/query/array/all' {
  declare module.exports: any;
}

declare module 'array-aggregate/lib/query/array/all.test' {
  declare module.exports: any;
}

declare module 'array-aggregate/lib/query/array/elemMatch' {
  declare module.exports: any;
}

declare module 'array-aggregate/lib/query/array/index' {
  declare module.exports: any;
}

declare module 'array-aggregate/lib/query/array/size' {
  declare module.exports: any;
}

declare module 'array-aggregate/lib/query/buildFilter' {
  declare module.exports: any;
}

declare module 'array-aggregate/lib/query/buildFilter.test' {
  declare module.exports: any;
}

declare module 'array-aggregate/lib/query/createMatcher' {
  declare module.exports: any;
}

declare module 'array-aggregate/lib/query/element/exists' {
  declare module.exports: any;
}

declare module 'array-aggregate/lib/query/element/index' {
  declare module.exports: any;
}

declare module 'array-aggregate/lib/query/fieldSelector' {
  declare module.exports: any;
}

declare module 'array-aggregate/lib/query/fieldSelector.test' {
  declare module.exports: any;
}

declare module 'array-aggregate/lib/query/index' {
  declare module.exports: any;
}

declare module 'array-aggregate/lib/query/logical/and' {
  declare module.exports: any;
}

declare module 'array-aggregate/lib/query/logical/and.test' {
  declare module.exports: any;
}

declare module 'array-aggregate/lib/query/logical/index' {
  declare module.exports: any;
}

declare module 'array-aggregate/lib/query/logical/nor' {
  declare module.exports: any;
}

declare module 'array-aggregate/lib/query/logical/nor.test' {
  declare module.exports: any;
}

declare module 'array-aggregate/lib/query/logical/not' {
  declare module.exports: any;
}

declare module 'array-aggregate/lib/query/logical/not.test' {
  declare module.exports: any;
}

declare module 'array-aggregate/lib/query/logical/or' {
  declare module.exports: any;
}

declare module 'array-aggregate/lib/query/logical/or.test' {
  declare module.exports: any;
}

declare module 'array-aggregate/lib/query/normalizeQuery' {
  declare module.exports: any;
}

declare module 'array-aggregate/lib/query/normalizeQuery.test' {
  declare module.exports: any;
}

declare module 'array-aggregate/lib/query/operators/eq' {
  declare module.exports: any;
}

declare module 'array-aggregate/lib/query/operators/gt' {
  declare module.exports: any;
}

declare module 'array-aggregate/lib/query/operators/gt.test' {
  declare module.exports: any;
}

declare module 'array-aggregate/lib/query/operators/gte' {
  declare module.exports: any;
}

declare module 'array-aggregate/lib/query/operators/in' {
  declare module.exports: any;
}

declare module 'array-aggregate/lib/query/operators/in.test' {
  declare module.exports: any;
}

declare module 'array-aggregate/lib/query/operators/index' {
  declare module.exports: any;
}

declare module 'array-aggregate/lib/query/operators/lt' {
  declare module.exports: any;
}

declare module 'array-aggregate/lib/query/operators/lte' {
  declare module.exports: any;
}

declare module 'array-aggregate/lib/query/operators/ne' {
  declare module.exports: any;
}

declare module 'array-aggregate/lib/query/operators/nin' {
  declare module.exports: any;
}

declare module 'array-aggregate/lib/query/types' {
  declare module.exports: any;
}

declare module 'array-aggregate/lib/query/validateQuery' {
  declare module.exports: any;
}

// Filename aliases
declare module 'array-aggregate/lib/index.js' {
  declare module.exports: $Exports<'array-aggregate/lib/index'>;
}
declare module 'array-aggregate/lib/makeQueryFilter.js' {
  declare module.exports: $Exports<'array-aggregate/lib/makeQueryFilter'>;
}
declare module 'array-aggregate/lib/query/array/all.js' {
  declare module.exports: $Exports<'array-aggregate/lib/query/array/all'>;
}
declare module 'array-aggregate/lib/query/array/all.test.js' {
  declare module.exports: $Exports<'array-aggregate/lib/query/array/all.test'>;
}
declare module 'array-aggregate/lib/query/array/elemMatch.js' {
  declare module.exports: $Exports<'array-aggregate/lib/query/array/elemMatch'>;
}
declare module 'array-aggregate/lib/query/array/index.js' {
  declare module.exports: $Exports<'array-aggregate/lib/query/array/index'>;
}
declare module 'array-aggregate/lib/query/array/size.js' {
  declare module.exports: $Exports<'array-aggregate/lib/query/array/size'>;
}
declare module 'array-aggregate/lib/query/buildFilter.js' {
  declare module.exports: $Exports<'array-aggregate/lib/query/buildFilter'>;
}
declare module 'array-aggregate/lib/query/buildFilter.test.js' {
  declare module.exports: $Exports<'array-aggregate/lib/query/buildFilter.test'>;
}
declare module 'array-aggregate/lib/query/createMatcher.js' {
  declare module.exports: $Exports<'array-aggregate/lib/query/createMatcher'>;
}
declare module 'array-aggregate/lib/query/element/exists.js' {
  declare module.exports: $Exports<'array-aggregate/lib/query/element/exists'>;
}
declare module 'array-aggregate/lib/query/element/index.js' {
  declare module.exports: $Exports<'array-aggregate/lib/query/element/index'>;
}
declare module 'array-aggregate/lib/query/fieldSelector.js' {
  declare module.exports: $Exports<'array-aggregate/lib/query/fieldSelector'>;
}
declare module 'array-aggregate/lib/query/fieldSelector.test.js' {
  declare module.exports: $Exports<'array-aggregate/lib/query/fieldSelector.test'>;
}
declare module 'array-aggregate/lib/query/index.js' {
  declare module.exports: $Exports<'array-aggregate/lib/query/index'>;
}
declare module 'array-aggregate/lib/query/logical/and.js' {
  declare module.exports: $Exports<'array-aggregate/lib/query/logical/and'>;
}
declare module 'array-aggregate/lib/query/logical/and.test.js' {
  declare module.exports: $Exports<'array-aggregate/lib/query/logical/and.test'>;
}
declare module 'array-aggregate/lib/query/logical/index.js' {
  declare module.exports: $Exports<'array-aggregate/lib/query/logical/index'>;
}
declare module 'array-aggregate/lib/query/logical/nor.js' {
  declare module.exports: $Exports<'array-aggregate/lib/query/logical/nor'>;
}
declare module 'array-aggregate/lib/query/logical/nor.test.js' {
  declare module.exports: $Exports<'array-aggregate/lib/query/logical/nor.test'>;
}
declare module 'array-aggregate/lib/query/logical/not.js' {
  declare module.exports: $Exports<'array-aggregate/lib/query/logical/not'>;
}
declare module 'array-aggregate/lib/query/logical/not.test.js' {
  declare module.exports: $Exports<'array-aggregate/lib/query/logical/not.test'>;
}
declare module 'array-aggregate/lib/query/logical/or.js' {
  declare module.exports: $Exports<'array-aggregate/lib/query/logical/or'>;
}
declare module 'array-aggregate/lib/query/logical/or.test.js' {
  declare module.exports: $Exports<'array-aggregate/lib/query/logical/or.test'>;
}
declare module 'array-aggregate/lib/query/normalizeQuery.js' {
  declare module.exports: $Exports<'array-aggregate/lib/query/normalizeQuery'>;
}
declare module 'array-aggregate/lib/query/normalizeQuery.test.js' {
  declare module.exports: $Exports<'array-aggregate/lib/query/normalizeQuery.test'>;
}
declare module 'array-aggregate/lib/query/operators/eq.js' {
  declare module.exports: $Exports<'array-aggregate/lib/query/operators/eq'>;
}
declare module 'array-aggregate/lib/query/operators/gt.js' {
  declare module.exports: $Exports<'array-aggregate/lib/query/operators/gt'>;
}
declare module 'array-aggregate/lib/query/operators/gt.test.js' {
  declare module.exports: $Exports<'array-aggregate/lib/query/operators/gt.test'>;
}
declare module 'array-aggregate/lib/query/operators/gte.js' {
  declare module.exports: $Exports<'array-aggregate/lib/query/operators/gte'>;
}
declare module 'array-aggregate/lib/query/operators/in.js' {
  declare module.exports: $Exports<'array-aggregate/lib/query/operators/in'>;
}
declare module 'array-aggregate/lib/query/operators/in.test.js' {
  declare module.exports: $Exports<'array-aggregate/lib/query/operators/in.test'>;
}
declare module 'array-aggregate/lib/query/operators/index.js' {
  declare module.exports: $Exports<'array-aggregate/lib/query/operators/index'>;
}
declare module 'array-aggregate/lib/query/operators/lt.js' {
  declare module.exports: $Exports<'array-aggregate/lib/query/operators/lt'>;
}
declare module 'array-aggregate/lib/query/operators/lte.js' {
  declare module.exports: $Exports<'array-aggregate/lib/query/operators/lte'>;
}
declare module 'array-aggregate/lib/query/operators/ne.js' {
  declare module.exports: $Exports<'array-aggregate/lib/query/operators/ne'>;
}
declare module 'array-aggregate/lib/query/operators/nin.js' {
  declare module.exports: $Exports<'array-aggregate/lib/query/operators/nin'>;
}
declare module 'array-aggregate/lib/query/types.js' {
  declare module.exports: $Exports<'array-aggregate/lib/query/types'>;
}
declare module 'array-aggregate/lib/query/validateQuery.js' {
  declare module.exports: $Exports<'array-aggregate/lib/query/validateQuery'>;
}
