# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
shared: &shared
  working_directory: ~/repo

  steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

    - run: yarn install
    - run: yarn global add codecov

    - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

    # run tests!
    - run: yarn test
    - run: yarn lint
    - run: yarn flow check
    - run: $(yarn global bin)/codecov

jobs:
  node_10_mariadb_10-3:
    <<: *shared
    docker:
      # specify the version you desire here
      - image: circleci/node:10
      - image: circleci/mariadb:10.3
        environment:
          MYSQL_DATABASE: minorm_test
          MYSQL_USER: local
          MYSQL_PASSWORD: freeware
          MYSQL_RANDOM_ROOT_PASSWORD: yes

  node_10_mysql_8:
    <<: *shared
    docker:
      # specify the version you desire here
      - image: circleci/node:10
      - image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_DATABASE: minorm_test
          MYSQL_USER: local
          MYSQL_PASSWORD: freeware
          MYSQL_RANDOM_ROOT_PASSWORD: yes

  node_8:
    <<: *shared
    docker:
      # specify the version you desire here
      - image: circleci/node:8
      - image: circleci/mariadb:10.3
        environment:
          MYSQL_DATABASE: minorm_test
          MYSQL_USER: local
          MYSQL_PASSWORD: freeware
          MYSQL_RANDOM_ROOT_PASSWORD: yes
  node_6:
    <<: *shared
    docker:
      # specify the version you desire here
      - image: circleci/node:6
      - image: circleci/mariadb:10.3
        environment:
          MYSQL_DATABASE: minorm_test
          MYSQL_USER: local
          MYSQL_PASSWORD: freeware
          MYSQL_RANDOM_ROOT_PASSWORD: yes
  version:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    parameters:
      is_next:
        type: boolean
        default: no
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - when:
          condition: <<parameters.is_next>>
          steps:
            - run: npm publish --tag next
      - unless:
          condition: <<parameters.is_next>>
          steps:
            - run: npm publish

workflows:
  version: 2
  build:
    jobs:
      - node_6
      - node_8
      - node_10_mariadb_10-3
      - node_10_mysql_8
      - version:
          requires:
            - node_6
            - node_8
            - node_10_mariadb_10-3
            - node_10_mysql_8
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v([0-9]+)\.([0-9]+)\.([0-9]+)$/
      - version:
          is_next: true
          requires:
            - node_6
            - node_8
            - node_10_mariadb_10-3
            - node_10_mysql_8
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v([0-9]+)\.([0-9]+)\.([0-9]+)@next$/
